#!/usr/bin/env python3
"""Generates com_vtables.inc: guest-side vtables for the COM interfaces the game
uses (Direct3D 9, DirectInput 8, DirectDraw 7, DirectSound), from the mingw-w64 SDK headers.

Each vtable slot is a trap. Methods whose arguments convert mechanically use
com::comThunk<&I::M>; methods listed in OVERRIDES are hand-written
(ovr_<Interface>_<Method>); methods with arguments the automatic thunk cannot
convert (callbacks, pointer-carrying structures) and no override trap with a
clear message.

usage: gen_com.py <sdk include dir> <out file>
"""
import re
import sys

INTERFACES = {
    "d3d9.h": [
        "IDirect3D9", "IDirect3DDevice9", "IDirect3DSwapChain9", "IDirect3DResource9", "IDirect3DSurface9",
        "IDirect3DVolume9", "IDirect3DBaseTexture9", "IDirect3DTexture9", "IDirect3DCubeTexture9",
        "IDirect3DVolumeTexture9", "IDirect3DVertexBuffer9", "IDirect3DIndexBuffer9", "IDirect3DVertexDeclaration9",
        "IDirect3DVertexShader9", "IDirect3DPixelShader9", "IDirect3DStateBlock9", "IDirect3DQuery9",
    ],
    "dinput.h": ["IDirectInput8A", "IDirectInput8W", "IDirectInputDevice8A", "IDirectInputDevice8W"],
    "ddraw.h": ["IDirectDraw7"],
    "dsound.h": [
        "IDirectSound", "IDirectSound8", "IDirectSoundBuffer", "IDirectSoundBuffer8", "IDirectSound3DBuffer",
        "IDirectSound3DListener", "IDirectSoundNotify", "IKsPropertySet",
    ],
}

OVERRIDES = {
    "IDirect3D9::CreateDevice", "IDirect3D9::GetAdapterModeCount", "IDirect3D9::EnumAdapterModes",
    "IDirect3D9::GetAdapterDisplayMode",
    "IDirect3DDevice9::Reset", "IDirect3DDevice9::Present", "IDirect3DDevice9::TestCooperativeLevel",
    "IDirect3DDevice9::CreateAdditionalSwapChain",
    "IDirect3DDevice9::GetCreationParameters",
    "IDirect3DSwapChain9::GetPresentParameters",
    "IDirect3DSurface9::LockRect", "IDirect3DSurface9::UnlockRect", "IDirect3DSurface9::GetContainer",
    "IDirect3DVolume9::LockBox", "IDirect3DVolume9::UnlockBox", "IDirect3DVolume9::GetContainer",
    "IDirect3DTexture9::LockRect", "IDirect3DTexture9::UnlockRect",
    "IDirect3DCubeTexture9::LockRect", "IDirect3DCubeTexture9::UnlockRect",
    "IDirect3DVolumeTexture9::LockBox", "IDirect3DVolumeTexture9::UnlockBox",
    "IDirect3DVertexBuffer9::Lock", "IDirect3DVertexBuffer9::Unlock",
    "IDirect3DIndexBuffer9::Lock", "IDirect3DIndexBuffer9::Unlock",
    "IDirectInput8A::EnumDevices", "IDirectInput8W::EnumDevices",
    "IDirectInputDevice8A::SetDataFormat", "IDirectInputDevice8W::SetDataFormat",
    "IDirectInputDevice8A::GetDeviceData", "IDirectInputDevice8W::GetDeviceData",
    "IDirectInputDevice8A::EnumObjects", "IDirectInputDevice8W::EnumObjects",
    "IDirectInputDevice8A::GetDeviceState", "IDirectInputDevice8W::GetDeviceState",
    "IDirectInputDevice8A::SetCooperativeLevel", "IDirectInputDevice8W::SetCooperativeLevel",
    "IDirectDraw7::GetAvailableVidMem",
    "IDirectSound::CreateSoundBuffer", "IDirectSound8::CreateSoundBuffer",
    "IDirectSoundBuffer::Lock", "IDirectSoundBuffer::Unlock", "IDirectSoundBuffer8::Lock", "IDirectSoundBuffer8::Unlock",
    "IDirectSoundNotify::SetNotificationPositions",
}

# Argument types the automatic thunk cannot convert.
UNSAFE = re.compile(
    r"CALLBACK|LPDIENUM|LPDICONFIGURE|DIACTIONFORMAT|DIEFFECT\b|LPCDIEFFECT|DIFILEEFFECT|DIDEVICEOBJECTDATA|"
    r"DIDATAFORMAT|D3DLOCKED_|D3DPRESENT_PARAMETERS|D3DDEVICE_CREATION_PARAMETERS|DIEFFESCAPE|"
    r"DIDEVICEIMAGEINFOHEADER|void\s*\*\*\s*ppContainer|LPDIRECTINPUTEFFECT|pInitializeFunction|"
    r"DDSURFACEDESC|LPDIRECTDRAWSURFACE|LPDIRECTDRAWCLIPPER|LPDIRECTDRAWPALETTE|"
    r"LPCDSBUFFERDESC|LPDSEFFECTDESC|LPVOID\s*\*\s*ppObject"
)
GENERIC = {"QueryInterface": "host::com::comQueryInterface", "AddRef": "host::com::comAddRef", "Release": "host::com::comRelease"}


def parse(path, wanted):
    text = open(path).read()
    out = {}
    for m in re.finditer(r"DECLARE_INTERFACE(?:_IID)?_\((\w+),\s*(\w+)(?:,\s*\"[^\"]*\")?\)\s*\{(.*?)\n\};", text, re.S):
        name, body = m.group(1), m.group(3)
        if name not in wanted:
            continue
        methods = []
        for mm in re.finditer(r"STDMETHOD(?:_\(\s*[^,]+,\s*(\w+)\)|\((\w+)\))\s*\((.*?)\)\s*PURE;", body, re.S):
            methods.append((mm.group(1) or mm.group(2), " ".join(mm.group(3).split())))
        out[name] = methods
    return out


def main():
    inc, outp = sys.argv[1], sys.argv[2]
    lines = ["// Generated by gen_com.py from the mingw-w64 SDK headers. Do not edit.", ""]
    regs = []
    for header, names in INTERFACES.items():
        parsed = parse(f"{inc}/{header}", set(names))
        for name in names:
            methods = parsed.get(name)
            if not methods:
                sys.exit(f"interface {name} not found in {header}")
            lines.append(f"template <> host::com::Class& host::com::classOf<{name}>() {{")
            lines.append(f"    static host::com::Class c = host::com::makeClass(\"{name}\", {{")
            for meth, args in methods:
                key = f"{name}::{meth}"
                if meth in GENERIC:
                    fn = GENERIC[meth]
                elif key in OVERRIDES:
                    fn = f"ovr_{name}_{meth}"
                elif UNSAFE.search(args):
                    fn = "nullptr"
                else:
                    fn = f"&host::com::comThunk<&{name}::{meth}>"
                lines.append(f"        {{\"{key}\", {fn}}},")
            lines.append("    });")
            lines.append("    return c;")
            lines.append("}")
            regs.append(name)
    decls = sorted({l.split('"')[1] for l in lines if "ovr_" in l})
    lines[2:2] = [f"void ovr_{k.replace('::', '_')}(Ctx* c);" for k in decls] + [""]
    lines.append("")
    lines.append("static const host::com::IidEntry kIids[] = {")
    for name in regs:
        lines.append(f"    {{&IID_{name}, [] {{ return &host::com::classOf<{name}>(); }}}},")
    lines.append("};")
    open(outp, "w").write("\n".join(lines) + "\n")
    print(f"{len(regs)} interfaces")


if __name__ == "__main__":
    main()
